import { useEffect, useState } from 'react';
import api from '../services/api';
import { useSchool } from '../context/SchoolContext';
import jsPDF from 'jspdf';

function PrincipalDashboard() {
  const [students, setStudents] = useState([]);
  const [activityLog, setActivityLog] = useState([]);
  const [loading, setLoading] = useState(true);
  
  // 🟢 GRAB THE SCHOOL ID FROM THE URL
  const { schoolId } = useSchool();

  useEffect(() => {
    const fetchData = async () => {
      try {
        // ✅ Append ?schoolId to the request
        const response = await api.get(`/api/students?schoolId=${schoolId}`);
        setStudents(response.data);
        
        const log = response.data.map(student => ({
          id: student.id,
          name: student.name,
          class: student.class,
          attendance: student.attendance || {},
          createdAt: student.createdAt
        }));
        setActivityLog(log);
      } catch (error) {
        console.error('Error fetching data:', error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [schoolId]);

  // PDF Generator (unchanged)
  const generatePDF = () => {
    const doc = new jsPDF();
    const today = new Date().toISOString().split('T')[0];
    
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185);
    doc.text('School Attendance Report', 105, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 30, { align: 'center' });
    
    const total = students.length;
    const present = students.filter(s => s.attendance && s.attendance[today] === 'present').length;
    const absent = students.filter(s => s.attendance && s.attendance[today] === 'absent').length;
    
    doc.setFontSize(14);
    doc.text(`Total: ${total}  |  Present: ${present}  |  Absent: ${absent}`, 105, 42, { align: 'center' });
    
    let y = 55;
    doc.setFillColor(41, 128, 185);
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.rect(10, y, 190, 10, 'F');
    doc.text('Name', 15, y + 7);
    doc.text('Class', 80, y + 7);
    doc.text('Roll', 130, y + 7);
    doc.text('Status', 165, y + 7);
    
    y += 12;
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    
    students.forEach((student, index) => {
      const status = student.attendance && student.attendance[today] 
        ? student.attendance[today].charAt(0).toUpperCase() + student.attendance[today].slice(1)
        : 'Not Marked';
      
      if (index % 2 === 0) {
        doc.setFillColor(240, 240, 240);
        doc.rect(10, y - 5, 190, 8, 'F');
      }
      
      doc.text(student.name, 15, y);
      doc.text(student.class, 80, y);
      doc.text(student.rollNo.toString(), 130, y);
      doc.text(status, 165, y);
      y += 8;
      
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    });
    
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by School Management System', 105, 290, { align: 'center' });
    
    doc.save(`Attendance_Report_${today}.pdf`);
  };

  if (loading) return <div style={{ textAlign: 'center', padding: '40px', color: '#fff' }}>⏳ Loading dashboard...</div>;

  return (
    <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
      {/* Principal Header */}
      <div style={{
        background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        color: 'white',
        padding: '25px',
        borderRadius: '20px',
        marginBottom: '25px',
        boxShadow: '0 10px 30px rgba(245, 87, 108, 0.4)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '15px'
      }}>
        <div>
          <h2 style={{ margin: 0 }}>👑 Principal Dashboard</h2>
          <p style={{ margin: '5px 0 0', opacity: 0.9 }}>Full overview of all school activities</p>
        </div>
        <button
          onClick={generatePDF}
          style={{
            padding: '12px 25px',
            backgroundColor: 'white',
            color: '#2c3e50',
            border: 'none',
            borderRadius: '12px',
            cursor: 'pointer',
            fontWeight: 'bold',
            fontSize: '16px',
            boxShadow: '0 4px 15px rgba(0,0,0,0.1)',
            transition: 'transform 0.2s'
          }}
          onMouseEnter={(e) => e.target.style.transform = 'scale(1.05)'}
          onMouseLeave={(e) => e.target.style.transform = 'scale(1)'}
        >
          📄 Download PDF Report
        </button>
      </div>

      {/* Stats Overview */}
      <div style={{ marginBottom: '25px' }}>
        <h3 style={{ color: '#fff', textShadow: '0 2px 4px rgba(0,0,0,0.2)' }}>📊 School Overview</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '15px' }}>
          <div style={{ backgroundColor: 'rgba(255, 255, 255, 0.95)', padding: '20px', borderRadius: '15px', textAlign: 'center', boxShadow: '0 4px 15px rgba(0,0,0,0.1)' }}>
            <h3 style={{ margin: 0, color: '#2c3e50' }}>{students.length}</h3>
            <p style={{ margin: 0, color: '#666' }}>Total Students</p>
          </div>
        </div>
      </div>

      {/* Activity Log */}
      <div>
        <h3 style={{ color: '#fff', textShadow: '0 2px 4px rgba(0,0,0,0.2)' }}>📋 All Student Activity</h3>
        <div style={{ maxHeight: '500px', overflowY: 'auto' }}>
          {activityLog.map((student) => (
            <div key={student.id} style={{
              padding: '20px',
              marginBottom: '15px',
              backgroundColor: 'rgba(255, 255, 255, 0.95)',
              borderRadius: '15px',
              boxShadow: '0 4px 15px rgba(0,0,0,0.1)'
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ fontWeight: 'bold', fontSize: '18px', color: '#2c3e50' }}>
                  {student.name} 
                  <span style={{ fontSize: '14px', fontWeight: 'normal', color: '#888', marginLeft: '10px' }}>(Class {student.class})</span>
                </span>
                <span style={{ color: '#888', fontSize: '14px' }}>Added: {new Date(student.createdAt).toLocaleString()}</span>
              </div>
              <div style={{ marginTop: '12px' }}>
                <strong style={{ color: '#555' }}>Attendance History:</strong>
                {Object.keys(student.attendance).length === 0 ? (
                  <span style={{ color: '#aaa', marginLeft: '10px' }}>No attendance recorded</span>
                ) : (
                  <div style={{ marginTop: '8px', display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                    {Object.entries(student.attendance).map(([date, status]) => (
                      <span key={date} style={{
                        padding: '6px 12px',
                        borderRadius: '20px',
                        backgroundColor: status === 'present' ? '#d4edda' : '#f8d7da',
                        color: status === 'present' ? '#155724' : '#721c24',
                        fontSize: '13px',
                        fontWeight: 'bold'
                      }}>
                        {date}: {status.toUpperCase()}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default PrincipalDashboard;